-- IMCAN Inventory Hub / Imkan Team
-- Supabase PostgreSQL initialization script.
-- Safe to run on an empty project. It does not drop or delete tables.
-- Default security: inventory is publicly readable for the anon dashboard;
-- writes and sensitive tables require authenticated Supabase users.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  open_id text not null unique,
  name text,
  email text,
  login_method text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.inventory_records (
  id bigint generated by default as identity primary key,
  source varchar(80) not null,
  country varchar(120) not null default '',
  city varchar(120) not null default '',
  router_name varchar(255) not null,
  old_router_name varchar(255) not null default '',
  site_id varchar(255) not null default '',
  subnet_ip varchar(255) not null default '',
  contact_details text,
  location text,
  operational_hours text,
  proactive_email_contacts text,
  switch_name varchar(255) not null default '',
  mcs_status varchar(120) not null default '',
  circuit_type varchar(255) not null default '',
  migration_status text not null default 'Not Migrated' check (migration_status in ('Migrated', 'Not Migrated')),
  serial_number varchar(255) not null default '',
  from_product_id varchar(255) not null default '',
  rack varchar(255) not null default '',
  port varchar(255) not null default '',
  vlan varchar(255) not null default '',
  to_vlan varchar(255) not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  user_name varchar(255) not null default 'System',
  action varchar(80) not null,
  entity_type varchar(80) not null,
  entity_id bigint,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_conversations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(255) not null default 'New AI conversation',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.ai_conversations(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists inventory_router_name_idx on public.inventory_records (lower(router_name));
create index if not exists inventory_site_id_idx on public.inventory_records (lower(site_id));
create index if not exists inventory_status_idx on public.inventory_records (migration_status);
create index if not exists inventory_country_idx on public.inventory_records (country);
create index if not exists inventory_source_idx on public.inventory_records (source);
create index if not exists audit_created_at_idx on public.audit_logs (created_at desc);
create index if not exists audit_action_idx on public.audit_logs (action);
create index if not exists audit_user_id_idx on public.audit_logs (user_id);
create index if not exists conversations_user_updated_idx on public.ai_conversations (user_id, updated_at desc);
create index if not exists messages_conversation_created_idx on public.ai_messages (conversation_id, created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists inventory_set_updated_at on public.inventory_records;
create trigger inventory_set_updated_at before update on public.inventory_records for each row execute function public.set_updated_at();
drop trigger if exists conversations_set_updated_at on public.ai_conversations;
create trigger conversations_set_updated_at before update on public.ai_conversations for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.users u
    where u.open_id = auth.uid()::text and u.role = 'admin'
  );
$$;

alter table public.users enable row level security;
alter table public.inventory_records enable row level security;
alter table public.audit_logs enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;

grant select on public.inventory_records to anon, authenticated;
grant select, insert, update, delete on public.users to authenticated;
grant select, insert, update, delete on public.audit_logs to authenticated;
grant select, insert, update, delete on public.ai_conversations to authenticated;
grant select, insert, update, delete on public.ai_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Inventory is readable by the anon dashboard. No anonymous writes are allowed.
drop policy if exists inventory_public_read on public.inventory_records;
create policy inventory_public_read on public.inventory_records for select to anon, authenticated using (true);
drop policy if exists inventory_admin_insert on public.inventory_records;
create policy inventory_admin_insert on public.inventory_records for insert to authenticated with check (public.is_admin());
drop policy if exists inventory_admin_update on public.inventory_records;
create policy inventory_admin_update on public.inventory_records for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists inventory_admin_delete on public.inventory_records;
create policy inventory_admin_delete on public.inventory_records for delete to authenticated using (public.is_admin());

-- User records are private and visible only to the matching user or an admin.
drop policy if exists users_self_read on public.users;
create policy users_self_read on public.users for select to authenticated using (open_id = auth.uid()::text or public.is_admin());
drop policy if exists users_admin_write on public.users;
create policy users_admin_write on public.users for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Audit logs are visible to admins; authenticated users may create an audit entry.
drop policy if exists audit_admin_read on public.audit_logs;
create policy audit_admin_read on public.audit_logs for select to authenticated using (public.is_admin());
drop policy if exists audit_authenticated_insert on public.audit_logs;
create policy audit_authenticated_insert on public.audit_logs for insert to authenticated with check (user_id is null or exists (select 1 from public.users u where u.id = user_id and u.open_id = auth.uid()::text));

-- AI conversations and messages are private to their owner; admins can review them.
drop policy if exists conversations_owner_read on public.ai_conversations;
create policy conversations_owner_read on public.ai_conversations for select to authenticated using (exists (select 1 from public.users u where u.id = user_id and u.open_id = auth.uid()::text) or public.is_admin());
drop policy if exists conversations_owner_write on public.ai_conversations;
create policy conversations_owner_write on public.ai_conversations for all to authenticated using (exists (select 1 from public.users u where u.id = user_id and u.open_id = auth.uid()::text) or public.is_admin()) with check (exists (select 1 from public.users u where u.id = user_id and u.open_id = auth.uid()::text) or public.is_admin());
drop policy if exists messages_owner_read on public.ai_messages;
create policy messages_owner_read on public.ai_messages for select to authenticated using (exists (select 1 from public.ai_conversations c join public.users u on u.id = c.user_id where c.id = conversation_id and (u.open_id = auth.uid()::text or public.is_admin())));
drop policy if exists messages_owner_write on public.ai_messages;
create policy messages_owner_write on public.ai_messages for all to authenticated using (exists (select 1 from public.ai_conversations c join public.users u on u.id = c.user_id where c.id = conversation_id and (u.open_id = auth.uid()::text or public.is_admin()))) with check (exists (select 1 from public.ai_conversations c join public.users u on u.id = c.user_id where c.id = conversation_id and (u.open_id = auth.uid()::text or public.is_admin())));

-- Optional compatibility view for simple dashboard queries.
create or replace view public.inventory_dashboard as
select
  id,
  source,
  country,
  city,
  router_name,
  site_id,
  subnet_ip,
  contact_details,
  location,
  operational_hours,
  proactive_email_contacts,
  circuit_type,
  migration_status,
  updated_at
from public.inventory_records;

grant select on public.inventory_dashboard to anon, authenticated;
